version: '3.6'

services:
  auth:
    build:
      context: ./auth
    ports:
      - "9001:9001"
    env_file:
      - ./.env

  resource:
    build:
      context: ./resource
    ports:
      - "9002:9002"
    env_file:
      - ./.env
    depends_on:
      - auth

  db:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - data:/data/db
    env_file:
      - ./.env
    depends_on:
      - auth
      - resource

volumes:
  data:

