version: '3.6'

services:
  auth:
    build:
      context: ./auth
    ports:
      - "9001:9001"
    env_file:
      - ./auth/.env

  resource:
    build:
      context: ./resource
    ports:
      - "9002:9002"
    env_file:
      - ./resource/.env
    depends_on:
      - auth
