version: '3.6'

services:
  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    ports:
      - "9001:9001"
    env_file:
      - ./.env
    networks:
      - go-oauth2-server_network

  resource:
    build:
      context: .
      dockerfile: ./resource/Dockerfile
    ports:
      - "9002:9002"
    env_file:
      - ./.env
    networks:
      - go-oauth2-server_network

  db:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - data:/data/db
    env_file:
      - ./.env
    depends_on:
      - auth
      - resource
    networks:
      - go-oauth2-server_network

volumes:
  data:

networks:
  go-oauth2-server_network:
    driver: "bridge"
